#!/usr/bin/env python3

import argparse
import psutil
import subprocess
import time


def numberOfChildrenOfPid(pid):
	return 1


def runCommandWhileProfiling(command, frequency, output):
	process = subprocess.Popen(command)
	pid = process.pid

	startTime = time.time()
	processCounts = [(startTime, numberOfChildrenOfPid(pid))]

	while process.poll() is None:
		time.sleep(frequency)
		currentTime = time.time()
		processCounts.append((currentTime, numberOfChildrenOfPid(pid)))

	return process.wait()


def main():
	parser = argparse.ArgumentParser(
		description="Get statistics for running command.")

	parser.add_argument(
		"--frequency", dest="frequency", type=int,
		help="How often to check statistics", default=1)

	parser.add_argument(
		"--output-file", dest="output", type=str,
		help="Where to place statistics file", default="cpugraph.out")

	parser.add_argument(
		"command", type=str, help="Command to profile", nargs="*")

	args = parser.parse_args()
	frequency = args.frequency
	output = args.output
	command = args.command

	return runCommandWhileProfiling(command, frequency, output)

if __name__ == "__main__":
	main()
